In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [80]:
import numpy as np
import pandas as pd

In [81]:
data=pd.read_csv("../input/titanic/train.csv")

In [82]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [83]:
x=data

In [84]:
x.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [85]:
x=x.drop(['PassengerId','Cabin','Ticket'],axis=1)
x.head()

Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch     Fare Embarked  
0    male  22.0      1      0   7.2500        S  
1  female  38.0      1      0  71.2833        C  
2  female  26.0      0      0   7.9250        S  
3  female  35.0      1      0  53.1000        S  
4    male  35.0      0      0   8.0500        S

In [86]:
y=x.iloc[:,:1].values

In [87]:
y

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
    

In [88]:
from sklearn.preprocessing import LabelEncoder

In [89]:
le=LabelEncoder()

In [90]:
x['Sex']=le.fit_transform(x.Sex)

In [91]:
x['Embarked']=le.fit_transform(x.Embarked)

TypeError: argument must be a string or number

In [92]:
x=x.drop(['Name'],axis=1)
x.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    1  22.0      1      0   7.2500        S
1         1       1    0  38.0      1      0  71.2833        C
2         1       3    0  26.0      0      0   7.9250        S
3         1       1    0  35.0      1      0  53.1000        S
4         0       3    1  35.0      0      0   8.0500        S

In [93]:
x.iloc[:,7:8]=x.iloc[:,7:8].apply(lambda x:x.fillna(x.value_counts().index[0]))

In [27]:
x.tail(25)

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
866         1       2    0  27.0      1      0  13.8583        S
867         0       1    1  31.0      0      0  50.4958        S
868         0       3    1   NaN      0      0   9.5000        S
869         1       3    1   4.0      1      1  11.1333        S
870         0       3    1  26.0      0      0   7.8958        S
871         1       1    0  47.0      1      1  52.5542        S
872         0       1    1  33.0      0      0   5.0000        S
873         0       3    1  47.0      0      0   9.0000        S
874         1       2    0  28.0      1      0  24.0000        S
875         1       3    0  15.0      0      0   7.2250        S
876         0       3    1  20.0      0      0   9.8458        S
877         0       3    1  19.0      0      0   7.8958        S
878         0       3    1   NaN      0      0   7.8958        S
879         1       1    0  56.0      0      1  83.1583        S
880         1       2    0  25.0      0      1  26.0000        S
881         0       3    1  33.0      0      0   7.8958        S
882         0       3    0  22.0      0      0  10.5167        S
883         0       2    1  28.0      0      0  10.5000        S
884         0       3    1  25.0      0      0   7.0500        S
885         0       3    0  39.0      0      5  29.1250        S
886         0       2    1  27.0      0      0  13.0000        S
887         1       1    0  19.0      0      0  30.0000        S
888         0       3    0   NaN      1      2  23.4500        S
889         1       1    1  26.0      0      0  30.0000        S
890         0       3    1  32.0      0      0   7.7500        S

In [94]:
x['Embarked']=le.fit_transform(x.Embarked)

In [95]:
x.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [96]:
df_x=x.iloc[:,1:8].values

In [97]:
df_x

array([[ 3.    ,  1.    , 22.    , ...,  0.    ,  7.25  ,  2.    ],
       [ 1.    ,  0.    , 38.    , ...,  0.    , 71.2833,  0.    ],
       [ 3.    ,  0.    , 26.    , ...,  0.    ,  7.925 ,  2.    ],
       ...,
       [ 3.    ,  0.    ,     nan, ...,  2.    , 23.45  ,  2.    ],
       [ 1.    ,  1.    , 26.    , ...,  0.    , 30.    ,  0.    ],
       [ 3.    ,  1.    , 32.    , ...,  0.    ,  7.75  ,  1.    ]])

In [98]:
from sklearn.impute import SimpleImputer

In [99]:
s=SimpleImputer(missing_values=np.nan,strategy='mean',verbose=0)

In [100]:
s=s.fit(df_x[:,:])

In [101]:
df_x[:,:]=s.transform(df_x[:,:])

In [102]:
df_x

array([[ 3.        ,  1.        , 22.        , ...,  0.        ,
         7.25      ,  2.        ],
       [ 1.        ,  0.        , 38.        , ...,  0.        ,
        71.2833    ,  0.        ],
       [ 3.        ,  0.        , 26.        , ...,  0.        ,
         7.925     ,  2.        ],
       ...,
       [ 3.        ,  0.        , 29.69911765, ...,  2.        ,
        23.45      ,  2.        ],
       [ 1.        ,  1.        , 26.        , ...,  0.        ,
        30.        ,  0.        ],
       [ 3.        ,  1.        , 32.        , ...,  0.        ,
         7.75      ,  1.        ]])

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
x_train,x_test,y_train,y_test=train_test_split(df_x,y,test_size=0.25,random_state=0)

In [105]:
import tensorflow as tf

In [106]:
import keras

In [107]:
from keras.models import Sequential

In [108]:
from keras.layers import Dense

In [109]:
classifier=Sequential()

In [110]:
classifier.add(Dense(output_dim=4,init='uniform',activation='relu',input_dim=7))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=7, units=4, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [111]:
classifier.add(Dense(output_dim=4,init='uniform',activation='relu'))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=4, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [112]:
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [113]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [114]:
from sklearn.preprocessing import StandardScaler

In [115]:
sc=StandardScaler()

In [116]:
x_train=sc.fit_transform(x_train)

In [117]:
x_test=sc.transform(x_test)

In [118]:
y_train

array([[0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
    

In [119]:
classifier.fit(x_train,y_train,batch_size=20,nb_epoch=1000)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/1000
668/668 [==============================] - 0s 323us/step - loss: 0.6919 - accuracy: 0.6093
Epoch 2/1000
668/668 [==============================] - 0s 65us/step - loss: 0.6883 - accuracy: 0.6138
Epoch 3/1000
668/668 [==============================] - 0s 63us/step - loss: 0.6828 - accuracy: 0.6138
Epoch 4/1000
668/668 [==============================] - 0s 64us/step - loss: 0.6735 - accuracy: 0.6138
Epoch 5/1000
668/668 [==============================] - 0s 66us/step - loss: 0.6590 - accuracy: 0.6153
Epoch 6/1000
668/668 [==============================] - 0s 66us/step - loss: 0.6387 - accuracy: 0.7036
Epoch 7/1000
668/668 [==============================] - 0s 66us/step - loss: 0.6135 - accuracy: 0.7754
Epoch 8/1000
668/668 [==============================] - 0s 64us/step - loss: 0.5853 - accuracy: 0.8009
Epoch 9/1000
668/668 [==============================] - 0s 64us/step - loss: 0.5578 - accuracy: 0.7979
Epoch 10/1000
668/668 [==============================] - 0s 65us/step - 

668/668 [==============================] - 0s 67us/step - loss: 0.4336 - accuracy: 0.8069
Epoch 80/1000
668/668 [==============================] - 0s 64us/step - loss: 0.4334 - accuracy: 0.8054
Epoch 81/1000
668/668 [==============================] - 0s 63us/step - loss: 0.4332 - accuracy: 0.8054
Epoch 82/1000
668/668 [==============================] - 0s 62us/step - loss: 0.4334 - accuracy: 0.8054
Epoch 83/1000
668/668 [==============================] - 0s 62us/step - loss: 0.4331 - accuracy: 0.8054
Epoch 84/1000
668/668 [==============================] - 0s 62us/step - loss: 0.4336 - accuracy: 0.8069
Epoch 85/1000
668/668 [==============================] - 0s 65us/step - loss: 0.4328 - accuracy: 0.8084
Epoch 86/1000
668/668 [==============================] - 0s 63us/step - loss: 0.4328 - accuracy: 0.8054
Epoch 87/1000
668/668 [==============================] - 0s 63us/step - loss: 0.4327 - accuracy: 0.8069
Epoch 88/1000
668/668 [==============================] - 0s 62us/step - loss: 

668/668 [==============================] - 0s 64us/step - loss: 0.4165 - accuracy: 0.8234
Epoch 158/1000
668/668 [==============================] - 0s 65us/step - loss: 0.4165 - accuracy: 0.8249
Epoch 159/1000
668/668 [==============================] - 0s 64us/step - loss: 0.4167 - accuracy: 0.8219
Epoch 160/1000
668/668 [==============================] - 0s 66us/step - loss: 0.4162 - accuracy: 0.8263
Epoch 161/1000
668/668 [==============================] - 0s 65us/step - loss: 0.4160 - accuracy: 0.8263
Epoch 162/1000
668/668 [==============================] - 0s 65us/step - loss: 0.4160 - accuracy: 0.8263
Epoch 163/1000
668/668 [==============================] - 0s 66us/step - loss: 0.4159 - accuracy: 0.8263
Epoch 164/1000
668/668 [==============================] - 0s 65us/step - loss: 0.4160 - accuracy: 0.8249
Epoch 165/1000
668/668 [==============================] - 0s 64us/step - loss: 0.4159 - accuracy: 0.8249
Epoch 166/1000
668/668 [==============================] - 0s 65us/step

668/668 [==============================] - 0s 65us/step - loss: 0.4129 - accuracy: 0.8338
Epoch 236/1000
668/668 [==============================] - 0s 62us/step - loss: 0.4123 - accuracy: 0.8353
Epoch 237/1000
668/668 [==============================] - 0s 64us/step - loss: 0.4119 - accuracy: 0.8338
Epoch 238/1000
668/668 [==============================] - 0s 63us/step - loss: 0.4124 - accuracy: 0.8398
Epoch 239/1000
668/668 [==============================] - 0s 63us/step - loss: 0.4120 - accuracy: 0.8368
Epoch 240/1000
668/668 [==============================] - 0s 62us/step - loss: 0.4119 - accuracy: 0.8368
Epoch 241/1000
668/668 [==============================] - 0s 63us/step - loss: 0.4123 - accuracy: 0.8353
Epoch 242/1000
668/668 [==============================] - 0s 66us/step - loss: 0.4125 - accuracy: 0.8368
Epoch 243/1000
668/668 [==============================] - 0s 68us/step - loss: 0.4122 - accuracy: 0.8353
Epoch 244/1000
668/668 [==============================] - 0s 67us/step

668/668 [==============================] - 0s 69us/step - loss: 0.4076 - accuracy: 0.8428
Epoch 314/1000
668/668 [==============================] - 0s 71us/step - loss: 0.4074 - accuracy: 0.8413
Epoch 315/1000
668/668 [==============================] - 0s 67us/step - loss: 0.4078 - accuracy: 0.8398
Epoch 316/1000
668/668 [==============================] - 0s 64us/step - loss: 0.4075 - accuracy: 0.8413
Epoch 317/1000
668/668 [==============================] - 0s 65us/step - loss: 0.4076 - accuracy: 0.8413
Epoch 318/1000
668/668 [==============================] - 0s 67us/step - loss: 0.4076 - accuracy: 0.8428
Epoch 319/1000
668/668 [==============================] - 0s 63us/step - loss: 0.4072 - accuracy: 0.8428
Epoch 320/1000
668/668 [==============================] - 0s 64us/step - loss: 0.4074 - accuracy: 0.8413
Epoch 321/1000
668/668 [==============================] - 0s 63us/step - loss: 0.4072 - accuracy: 0.8398
Epoch 322/1000
668/668 [==============================] - 0s 68us/step

668/668 [==============================] - 0s 65us/step - loss: 0.4056 - accuracy: 0.8443
Epoch 392/1000
668/668 [==============================] - 0s 64us/step - loss: 0.4061 - accuracy: 0.8428
Epoch 393/1000
668/668 [==============================] - 0s 63us/step - loss: 0.4057 - accuracy: 0.8428
Epoch 394/1000
668/668 [==============================] - 0s 63us/step - loss: 0.4059 - accuracy: 0.8428
Epoch 395/1000
668/668 [==============================] - 0s 64us/step - loss: 0.4059 - accuracy: 0.8413
Epoch 396/1000
668/668 [==============================] - 0s 64us/step - loss: 0.4057 - accuracy: 0.8443
Epoch 397/1000
668/668 [==============================] - 0s 62us/step - loss: 0.4060 - accuracy: 0.8443
Epoch 398/1000
668/668 [==============================] - 0s 68us/step - loss: 0.4057 - accuracy: 0.8398
Epoch 399/1000
668/668 [==============================] - 0s 67us/step - loss: 0.4058 - accuracy: 0.8428
Epoch 400/1000
668/668 [==============================] - 0s 63us/step

668/668 [==============================] - 0s 73us/step - loss: 0.4026 - accuracy: 0.8458
Epoch 470/1000
668/668 [==============================] - 0s 70us/step - loss: 0.4023 - accuracy: 0.8413
Epoch 471/1000
668/668 [==============================] - 0s 69us/step - loss: 0.4025 - accuracy: 0.8443
Epoch 472/1000
668/668 [==============================] - 0s 66us/step - loss: 0.4026 - accuracy: 0.8413
Epoch 473/1000
668/668 [==============================] - 0s 70us/step - loss: 0.4020 - accuracy: 0.8443
Epoch 474/1000
668/668 [==============================] - 0s 70us/step - loss: 0.4020 - accuracy: 0.8428
Epoch 475/1000
668/668 [==============================] - 0s 72us/step - loss: 0.4018 - accuracy: 0.8413
Epoch 476/1000
668/668 [==============================] - 0s 71us/step - loss: 0.4019 - accuracy: 0.8443
Epoch 477/1000
668/668 [==============================] - 0s 71us/step - loss: 0.4014 - accuracy: 0.8413
Epoch 478/1000
668/668 [==============================] - 0s 70us/step

668/668 [==============================] - 0s 63us/step - loss: 0.3983 - accuracy: 0.8428
Epoch 548/1000
668/668 [==============================] - 0s 66us/step - loss: 0.3982 - accuracy: 0.8428
Epoch 549/1000
668/668 [==============================] - 0s 70us/step - loss: 0.3977 - accuracy: 0.8428
Epoch 550/1000
668/668 [==============================] - 0s 65us/step - loss: 0.3980 - accuracy: 0.8413
Epoch 551/1000
668/668 [==============================] - 0s 65us/step - loss: 0.3975 - accuracy: 0.8428
Epoch 552/1000
668/668 [==============================] - 0s 62us/step - loss: 0.3980 - accuracy: 0.8428
Epoch 553/1000
668/668 [==============================] - 0s 62us/step - loss: 0.3976 - accuracy: 0.8383
Epoch 554/1000
668/668 [==============================] - 0s 65us/step - loss: 0.3976 - accuracy: 0.8398
Epoch 555/1000
668/668 [==============================] - 0s 66us/step - loss: 0.3977 - accuracy: 0.8383
Epoch 556/1000
668/668 [==============================] - 0s 65us/step

668/668 [==============================] - 0s 64us/step - loss: 0.3937 - accuracy: 0.8383
Epoch 626/1000
668/668 [==============================] - 0s 65us/step - loss: 0.3943 - accuracy: 0.8383
Epoch 627/1000
668/668 [==============================] - 0s 64us/step - loss: 0.3929 - accuracy: 0.8338
Epoch 628/1000
668/668 [==============================] - 0s 68us/step - loss: 0.3935 - accuracy: 0.8338
Epoch 629/1000
668/668 [==============================] - 0s 65us/step - loss: 0.3933 - accuracy: 0.8383
Epoch 630/1000
668/668 [==============================] - 0s 69us/step - loss: 0.3936 - accuracy: 0.8353
Epoch 631/1000
668/668 [==============================] - 0s 67us/step - loss: 0.3936 - accuracy: 0.8383
Epoch 632/1000
668/668 [==============================] - 0s 65us/step - loss: 0.3930 - accuracy: 0.8368
Epoch 633/1000
668/668 [==============================] - 0s 69us/step - loss: 0.3933 - accuracy: 0.8338
Epoch 634/1000
668/668 [==============================] - 0s 67us/step

668/668 [==============================] - 0s 66us/step - loss: 0.3910 - accuracy: 0.8428
Epoch 704/1000
668/668 [==============================] - 0s 66us/step - loss: 0.3910 - accuracy: 0.8428
Epoch 705/1000
668/668 [==============================] - 0s 71us/step - loss: 0.3907 - accuracy: 0.8413
Epoch 706/1000
668/668 [==============================] - 0s 77us/step - loss: 0.3905 - accuracy: 0.8398
Epoch 707/1000
668/668 [==============================] - 0s 75us/step - loss: 0.3907 - accuracy: 0.8398
Epoch 708/1000
668/668 [==============================] - 0s 72us/step - loss: 0.3916 - accuracy: 0.8428
Epoch 709/1000
668/668 [==============================] - 0s 63us/step - loss: 0.3903 - accuracy: 0.8428
Epoch 710/1000
668/668 [==============================] - 0s 66us/step - loss: 0.3902 - accuracy: 0.8413
Epoch 711/1000
668/668 [==============================] - 0s 65us/step - loss: 0.3904 - accuracy: 0.8413
Epoch 712/1000
668/668 [==============================] - 0s 67us/step

668/668 [==============================] - 0s 66us/step - loss: 0.3873 - accuracy: 0.8413
Epoch 782/1000
668/668 [==============================] - 0s 69us/step - loss: 0.3871 - accuracy: 0.8428
Epoch 783/1000
668/668 [==============================] - 0s 67us/step - loss: 0.3870 - accuracy: 0.8413
Epoch 784/1000
668/668 [==============================] - 0s 66us/step - loss: 0.3873 - accuracy: 0.8428
Epoch 785/1000
668/668 [==============================] - 0s 76us/step - loss: 0.3870 - accuracy: 0.8413
Epoch 786/1000
668/668 [==============================] - 0s 73us/step - loss: 0.3871 - accuracy: 0.8413
Epoch 787/1000
668/668 [==============================] - 0s 66us/step - loss: 0.3868 - accuracy: 0.8398
Epoch 788/1000
668/668 [==============================] - 0s 63us/step - loss: 0.3872 - accuracy: 0.8398
Epoch 789/1000
668/668 [==============================] - 0s 63us/step - loss: 0.3875 - accuracy: 0.8428
Epoch 790/1000
668/668 [==============================] - 0s 64us/step

668/668 [==============================] - 0s 64us/step - loss: 0.3859 - accuracy: 0.8398
Epoch 860/1000
668/668 [==============================] - 0s 65us/step - loss: 0.3863 - accuracy: 0.8473
Epoch 861/1000
668/668 [==============================] - 0s 63us/step - loss: 0.3858 - accuracy: 0.8488
Epoch 862/1000
668/668 [==============================] - 0s 64us/step - loss: 0.3858 - accuracy: 0.8458
Epoch 863/1000
668/668 [==============================] - 0s 67us/step - loss: 0.3856 - accuracy: 0.8428
Epoch 864/1000
668/668 [==============================] - 0s 66us/step - loss: 0.3854 - accuracy: 0.8473
Epoch 865/1000
668/668 [==============================] - 0s 63us/step - loss: 0.3853 - accuracy: 0.8413
Epoch 866/1000
668/668 [==============================] - 0s 64us/step - loss: 0.3851 - accuracy: 0.8428
Epoch 867/1000
668/668 [==============================] - 0s 66us/step - loss: 0.3856 - accuracy: 0.8458
Epoch 868/1000
668/668 [==============================] - 0s 66us/step

668/668 [==============================] - 0s 64us/step - loss: 0.3845 - accuracy: 0.8458
Epoch 938/1000
668/668 [==============================] - 0s 66us/step - loss: 0.3849 - accuracy: 0.8458
Epoch 939/1000
668/668 [==============================] - 0s 68us/step - loss: 0.3847 - accuracy: 0.8413
Epoch 940/1000
668/668 [==============================] - 0s 68us/step - loss: 0.3846 - accuracy: 0.8428
Epoch 941/1000
668/668 [==============================] - 0s 68us/step - loss: 0.3843 - accuracy: 0.8443
Epoch 942/1000
668/668 [==============================] - 0s 67us/step - loss: 0.3843 - accuracy: 0.8473
Epoch 943/1000
668/668 [==============================] - 0s 67us/step - loss: 0.3842 - accuracy: 0.8473
Epoch 944/1000
668/668 [==============================] - 0s 67us/step - loss: 0.3845 - accuracy: 0.8473
Epoch 945/1000
668/668 [==============================] - 0s 67us/step - loss: 0.3853 - accuracy: 0.8488
Epoch 946/1000
668/668 [==============================] - 0s 67us/step

In [120]:
y_pred=classifier.predict(x_test)

In [121]:
y_pred

array([[0.17538437],
       [0.09540212],
       [0.13887672],
       [0.9629195 ],
       [0.49011293],
       [0.30441213],
       [0.9485623 ],
       [0.8648216 ],
       [0.403567  ],
       [0.7823166 ],
       [0.06794314],
       [0.8875945 ],
       [0.14467971],
       [0.94273293],
       [0.9616677 ],
       [0.64554465],
       [0.12133033],
       [0.51306057],
       [0.08090086],
       [0.81387776],
       [0.19561711],
       [0.8997102 ],
       [0.1446607 ],
       [0.30181476],
       [0.64085424],
       [0.95990247],
       [0.0886178 ],
       [0.63603663],
       [0.9223189 ],
       [0.41777176],
       [0.16662268],
       [0.7880878 ],
       [0.10318843],
       [0.27902007],
       [0.06064674],
       [0.32009277],
       [0.07105181],
       [0.12540728],
       [0.13513564],
       [0.08657517],
       [0.2727486 ],
       [0.18835253],
       [0.10324516],
       [0.0314474 ],
       [0.9898358 ],
       [0.09576958],
       [0.09576958],
       [0.603

In [122]:
y_test

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
    

In [123]:
(y_pred > 0.5).astype(int)

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
    

In [124]:
from sklearn.metrics import confusion_matrix

In [126]:
dp=pd.read_csv("../input/titanic/test.csv")

In [127]:
dp.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [148]:
x1=dp.iloc[:,0:1].values

In [149]:
x1

array([[ 892],
       [ 893],
       [ 894],
       [ 895],
       [ 896],
       [ 897],
       [ 898],
       [ 899],
       [ 900],
       [ 901],
       [ 902],
       [ 903],
       [ 904],
       [ 905],
       [ 906],
       [ 907],
       [ 908],
       [ 909],
       [ 910],
       [ 911],
       [ 912],
       [ 913],
       [ 914],
       [ 915],
       [ 916],
       [ 917],
       [ 918],
       [ 919],
       [ 920],
       [ 921],
       [ 922],
       [ 923],
       [ 924],
       [ 925],
       [ 926],
       [ 927],
       [ 928],
       [ 929],
       [ 930],
       [ 931],
       [ 932],
       [ 933],
       [ 934],
       [ 935],
       [ 936],
       [ 937],
       [ 938],
       [ 939],
       [ 940],
       [ 941],
       [ 942],
       [ 943],
       [ 944],
       [ 945],
       [ 946],
       [ 947],
       [ 948],
       [ 949],
       [ 950],
       [ 951],
       [ 952],
       [ 953],
       [ 954],
       [ 955],
       [ 956],
       [ 957],
       [ 9

In [131]:
t=dp.drop(['PassengerId','Name','Cabin','Ticket'],axis=1)

In [132]:
t.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

In [133]:
t['Sex']=le.fit_transform(t.Sex)

In [134]:
t['Embarked']=le.fit_transform(t.Embarked)

In [135]:
t.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  34.5      0      0   7.8292         1
1       3    0  47.0      1      0   7.0000         2
2       2    1  62.0      0      0   9.6875         1
3       3    1  27.0      0      0   8.6625         2
4       3    0  22.0      1      1  12.2875         2

In [136]:
t=t.iloc[:,:].values

In [137]:
t=sc.fit_transform(t)

In [138]:
predd=classifier.predict(t)

In [139]:
predd

array([[1.20032571e-01],
       [1.47393912e-01],
       [1.01227209e-01],
       [1.04080170e-01],
       [1.67398199e-01],
       [1.53872877e-01],
       [6.74042106e-01],
       [1.37737706e-01],
       [6.02540135e-01],
       [4.31244522e-02],
       [           nan],
       [2.30606899e-01],
       [9.94709969e-01],
       [4.72536981e-02],
       [9.85808671e-01],
       [9.91019666e-01],
       [1.43444955e-01],
       [1.97130039e-01],
       [3.25053722e-01],
       [7.37345815e-01],
       [5.51357448e-01],
       [5.19748330e-01],
       [           nan],
       [3.11968148e-01],
       [9.23290431e-01],
       [3.67809087e-02],
       [9.69560921e-01],
       [1.93114132e-01],
       [2.29421720e-01],
       [           nan],
       [5.76803274e-02],
       [5.03607690e-02],
       [1.07365571e-01],
       [           nan],
       [6.70571566e-01],
       [2.34976694e-01],
       [           nan],
       [5.66034913e-01],
       [1.11512832e-01],
       [           nan],


In [140]:
(predd > 0.5).astype(int)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [147]:
m1=pd.DataFrame(predd,columns=['Survived'])

In [150]:
x1=pd.DataFrame(x1,columns=['PassengerId'])

In [151]:
sb=pd.concat([x1,m1],axis=1)

In [152]:
sb.head()

PassengerId  Survived
0          892  0.120033
1          893  0.147394
2          894  0.101227
3          895  0.104080
4          896  0.167398

In [ ]:
sb.to_csv('submissionbest.csv', index=False)